# Setup
title: rustandbone
tagline: "Developer"
description: 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: "https://rustandbone.github.io/dev_blog"
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Dongho Lee
  url: https://github.com/rustandbone
  email: dlehdgh14@naver.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
